import { describe, expect, it } from 'vitest';
import { ZcodeAdapter } from '../src/adapters/zcode.js';
import type { ZcodeClientLike } from '../src/adapters/zcode-protocol.js';
// Unit; verifies unloaded native state never becomes a rejected/lost V4 input. <1s/max5s.
describe('ZCode exact cold load before V4 admission',()=>{
 function fixture(wrongId=false,transportError=false,runtimeUnavailable=false){let loaded=false;const calls:string[]=[];const client:ZcodeClientLike={async start(){},async close(){},async call(_channel,method,args){calls.push(method);const params=args[0] as any;if(method==='readSession'){if(transportError)throw Error('transport disconnected');if(!loaded)throw runtimeUnavailable ? Object.assign(Error('ZCode Agent runtime is not running.'), {code:'ZCODE_AGENT_RUNTIME_UNAVAILABLE'}) : Error('Session not found');return{session:{sessionId:'owned',status:'idle'},runtime:{pendingRequestIds:[]}}}if(method==='resumeSession'){loaded=true;return{session:{sessionId:wrongId?'foreign':'owned',status:'idle'},runtime:{pendingRequestIds:[]}}}if(method==='sendConversationCommandV4'){return{commandId:params.envelope.commandId,status:loaded?'accepted':'rejected',reasonCode:'proto.sessionNotFound',result:loaded?{type:'inputAccepted',inputId:'one',delivery:'startNow'}:undefined}}throw Error('Unexpected '+method)}};return{calls,adapter:new ZcodeAdapter({client,cwd:'/workspace',localDbPath:'/missing',tasksIndexDbPath:'/missing'})}}
 it('loads the same ID without a prompt before issuing one command',async()=>{const f=fixture();expect(await f.adapter.sendMessage('owned',{message:'decision',inputId:'one',origin:'human',steer:true})).toMatchObject({ok:true,admitted:true});expect(f.calls).toEqual(['readSession','resumeSession','readSession','sendConversationCommandV4'])});
 it('loads a confirmed unavailable workspace runtime before the first input',async()=>{const f=fixture(false,false,true);expect(await f.adapter.sendMessage('owned',{message:'decision',inputId:'one',origin:'human',steer:true})).toMatchObject({ok:true,admitted:true});expect(f.calls.filter(x=>x==='sendConversationCommandV4')).toHaveLength(1)});
 it('rejects a different resumed identity before mutation',async()=>{const f=fixture(true);expect(await f.adapter.sendMessage('owned',{message:'decision',inputId:'one',origin:'human',steer:true})).toMatchObject({ok:false});expect(f.calls).not.toContain('sendConversationCommandV4')});
 it('does not treat transport failure as proof of an unloaded session',async()=>{const f=fixture(false,true);expect(await f.adapter.sendMessage('owned',{message:'decision',inputId:'one',origin:'human',steer:true})).toMatchObject({ok:false});expect(f.calls).not.toContain('resumeSession');expect(f.calls).not.toContain('sendConversationCommandV4')});
});
