import type { McpServer } from "@modelcontextprotocol/server";
import { z } from "zod";
import type { HerderJobRegistry } from "../herder-jobs.js";
import type {
  CdpChatCapabilities, DownloadMediaInput, EditMessageInput, ExportChatInput, ListChatsInput, NewChatInput, SearchChatInput, SendMessageInput,
} from "../cdp-chat.js";
import { CdpChatClient } from "../cdp-chat.js";
import { ChatGptAccountArchive, type ImportAccountExportInput, type RequestAccountExportInput } from "../chatgpt-account-archive.js";
import { ChatGptHistoryArchive, type ExportChatHistoryInput, type ExportVisibleChatHistoryInput, type ListChatHistoryInput, type ReconcileVisibleChatHistoryInput } from "../chatgpt-history-archive.js";
import { startJobResult, structuredValueResult } from "./results.js";

export function registerCdpTools(server: McpServer, deps: {
  client?: CdpChatClient;
  capabilities?: CdpChatCapabilities;
  accountArchive?: ChatGptAccountArchive;
  historyArchive?: ChatGptHistoryArchive;
  jobs: HerderJobRegistry;
}): void {
  const { client, capabilities, accountArchive, historyArchive, jobs } = deps;
  if (client && capabilities) registerFixtureTools(server, client, capabilities);
  if (historyArchive) registerHistoryArchiveTools(server, historyArchive, jobs);
  if (accountArchive) registerAccountArchiveTools(server, accountArchive, jobs);
}

function registerFixtureTools(server: McpServer, client: CdpChatClient, capabilities: CdpChatCapabilities): void {
  if (capabilities.new_chat) server.registerTool("cdp_new_chat", { description: "Create exactly one disposable chat on the owned authenticated page without submitting a prompt.", inputSchema: z.object({ confirmation: z.literal("NEW_CHAT"), idempotencyKey: z.string().min(1).max(128), title: z.string().min(1).max(256).optional() }) }, async (args) => structuredValueResult(await client.newChat(args as NewChatInput)));
  if (capabilities.list_chats) server.registerTool("cdp_list_chats", { description: "List page-visible chats by explicit unread, observable working, or UTC-recent semantics with bounded pagination.", inputSchema: z.object({ view: z.enum(["unread", "working", "recent"]), limit: z.number().int().min(1).max(100).optional(), cursor: z.string().max(128).optional() }) }, async (args) => structuredValueResult(await client.listChats(args as ListChatsInput)));
  if (capabilities.search_chat) server.registerTool("cdp_search_chat", { description: "Search page-visible chat titles and message text using one fresh owned-page snapshot.", inputSchema: z.object({ query: z.string().trim().min(1).max(256), limit: z.number().int().min(1).max(100).optional() }) }, async (args) => structuredValueResult(await client.searchChat(args as SearchChatInput)));
  if (capabilities.export_chat) server.registerTool("cdp_export_chat", { description: "Export only a fixture-bound chat with bounded message count and UTF-8 byte output.", inputSchema: z.object({ chatRef: z.string().min(1).max(256), format: z.enum(["json", "markdown"]), maxMessages: z.number().int().min(1).max(100).optional() }) }, async (args) => structuredValueResult(await client.exportChat(args as ExportChatInput)));
  if (capabilities.send_message) server.registerTool("cdp_send_message", { description: "Send one fixture message only with exact confirmation SEND_MESSAGE and a one-shot idempotency gate.", inputSchema: z.object({ chatRef: z.string().min(1).max(256), text: z.string().min(1).max(100_000), confirmation: z.literal("SEND_MESSAGE"), idempotencyKey: z.string().min(1).max(128) }) }, async (args) => structuredValueResult(await client.sendMessage(args as SendMessageInput)));
  if (capabilities.edit_message) server.registerTool("cdp_edit_message", { description: "Edit one fixture message only with exact confirmation EDIT_MESSAGE, one-shot idempotency, and an expected version or old-text guard.", inputSchema: z.object({ chatRef: z.string().min(1).max(256), messageRef: z.string().min(1).max(256), text: z.string().min(1).max(100_000), confirmation: z.literal("EDIT_MESSAGE"), idempotencyKey: z.string().min(1).max(128), expectedVersion: z.number().int().min(1).optional(), expectedText: z.string().max(100_000).optional() }) }, async (args) => structuredValueResult(await client.editMessage(args as EditMessageInput)));
  if (capabilities.download_media) server.registerTool("cdp_download_media", { description: "Download one fixture attachment of an allowlisted MIME and size into the confined media root.", inputSchema: z.object({ chatRef: z.string().min(1).max(256), messageRef: z.string().min(1).max(256), mediaRef: z.string().min(1).max(256), outputDir: z.string().max(4096).optional() }) }, async (args) => structuredValueResult(await client.downloadMedia(args as DownloadMediaInput)));
}

function registerAccountArchiveTools(server: McpServer, archive: ChatGptAccountArchive, jobs: HerderJobRegistry): void {
  server.registerTool("cdp_request_account_export", { description: "Request ChatGPT's official account-data ZIP. The link arrives by email or SMS; no chat prompt is sent.", inputSchema: z.object({ confirmation: z.literal("REQUEST_ACCOUNT_EXPORT") }) }, async (args) => structuredValueResult(await archive.requestAccountExport(args as RequestAccountExportInput)));
  server.registerTool("cdp_request_account_export_async", { description: "Start the ChatGPT official account-export request as a Herder job and return immediately with a durable job reference.", inputSchema: z.object({ confirmation: z.literal("REQUEST_ACCOUNT_EXPORT"), ownerSessionId: z.string().optional() }) }, async (args) => startJobResult(jobs, "chatgpt-account-export-request", async (signal, progress) => { progress(0.15, "Requesting account export"); return archive.requestAccountExport(args as RequestAccountExportInput, signal); }, args.ownerSessionId));
  server.registerTool("cdp_import_account_export", { description: "Copy a downloaded ChatGPT account-export ZIP into the local archive and create a source-format manifest without converting chat content.", inputSchema: z.object({ sourcePath: z.string().min(1).max(4096) }) }, async (args) => structuredValueResult(await archive.importAccountExport(args as ImportAccountExportInput)));
  server.registerTool("cdp_import_account_export_async", { description: "Import a downloaded ChatGPT account-export ZIP as a Herder background job.", inputSchema: z.object({ sourcePath: z.string().min(1).max(4096), ownerSessionId: z.string().optional() }) }, async (args) => startJobResult(jobs, "chatgpt-account-export-import", async (signal, progress) => { progress(0.1, "Importing account archive"); return archive.importAccountExport(args as ImportAccountExportInput, signal); }, args.ownerSessionId));
  server.registerTool("cdp_list_account_exports", { description: "List imported ChatGPT account-export ZIP archives and aggregate entry categories without exposing chat text.", inputSchema: z.object({ limit: z.number().int().min(1).max(100).optional() }) }, async (args) => structuredValueResult(await archive.listAccountExports(args.limit)));
}

function registerHistoryArchiveTools(server: McpServer, archive: ChatGptHistoryArchive, jobs: HerderJobRegistry): void {
  server.registerTool("cdp_reconcile_known_routes", { description: "Materialize local Markdown and HTML from all already captured ChatGPT /c/... snapshots. This never opens, scrolls, or alters ChatGPT and works while BrowserClaw is unavailable.", inputSchema: z.object({}) }, async () => structuredValueResult(await archive.reconcileKnownRoutes()));
  server.registerTool("cdp_reconcile_known_routes_async", { description: "Reconcile all captured ChatGPT routes as a Herder background job.", inputSchema: z.object({ ownerSessionId: z.string().optional() }) }, async (args) => startJobResult(jobs, "chatgpt-history-reconcile-known", async (signal, progress) => { progress(0.1, "Reconciling captured routes"); return archive.reconcileKnownRoutes(signal); }, args.ownerSessionId));
  server.registerTool("cdp_list_chats", { description: "List the currently visible ChatGPT sidebar chats from the one owned page. No chat content is returned.", inputSchema: z.object({ view: z.enum(["unread", "working", "recent"]), limit: z.number().int().min(1).max(100).optional() }) }, async (args) => structuredValueResult(await archive.listChats(args as ListChatHistoryInput)));
  server.registerTool("cdp_export_chat", { description: "Read one listed ChatGPT chat in the same owned page, scroll backward, and save raw snapshots locally. Returns only a checkpoint receipt.", inputSchema: z.object({ chatRef: z.string().min(1).max(256), maxSegments: z.number().int().min(1).max(100).optional() }) }, async (args) => structuredValueResult(await archive.exportChat(args as ExportChatHistoryInput)));
  server.registerTool("cdp_export_chat_async", { description: "Export one ChatGPT chat as a Herder background job.", inputSchema: z.object({ chatRef: z.string().min(1).max(256), maxSegments: z.number().int().min(1).max(100).optional(), ownerSessionId: z.string().optional() }) }, async (args) => startJobResult(jobs, "chatgpt-history-export-chat", async (signal, progress) => { progress(0.08, "Exporting chat history"); return archive.exportChat(args as ExportChatHistoryInput, signal); }, args.ownerSessionId));
  server.registerTool("cdp_export_visible_chats", { description: "Best-effort export of all currently visible non-protected ChatGPT conversations. Completed archives include local Markdown and HTML renderings beside raw snapshots.", inputSchema: z.object({ maxChats: z.number().int().min(1).max(100).optional(), maxSegmentsPerChat: z.number().int().min(1).max(100).optional() }) }, async (args) => structuredValueResult(await archive.exportVisibleChats(args as ExportVisibleChatHistoryInput)));
  server.registerTool("cdp_export_visible_chats_async", { description: "Export all currently visible ChatGPT conversations as a Herder background job.", inputSchema: z.object({ maxChats: z.number().int().min(1).max(100).optional(), maxSegmentsPerChat: z.number().int().min(1).max(100).optional(), ownerSessionId: z.string().optional() }) }, async (args) => startJobResult(jobs, "chatgpt-history-export-visible", async (signal, progress) => { progress(0.05, "Exporting visible chats"); return archive.exportVisibleChats(args as ExportVisibleChatHistoryInput, signal); }, args.ownerSessionId));
  server.registerTool("cdp_reconcile_visible_chats", { description: "Materialize local Markdown and HTML from already captured ChatGPT history snapshots for the currently visible chats. This does not open, scroll, or alter ChatGPT.", inputSchema: z.object({ maxChats: z.number().int().min(1).max(100).optional() }) }, async (args) => structuredValueResult(await archive.reconcileVisibleChats(args as ReconcileVisibleChatHistoryInput)));
  server.registerTool("cdp_reconcile_visible_chats_async", { description: "Reconcile currently visible captured ChatGPT chats as a Herder background job.", inputSchema: z.object({ maxChats: z.number().int().min(1).max(100).optional(), ownerSessionId: z.string().optional() }) }, async (args) => startJobResult(jobs, "chatgpt-history-reconcile-visible", async (signal, progress) => { progress(0.1, "Reconciling visible chats"); return archive.reconcileVisibleChats(args as ReconcileVisibleChatHistoryInput, signal); }, args.ownerSessionId));
}
