import type { SessionDetails } from "./types/index.js";

function jsonForHtml(value: unknown): string {
  return JSON.stringify(value).replace(/</g, "\\u003c");
}

/** Render canonical session data as the interactive message/file graph used by the audit tool. */
export function renderSessionGraph(details: SessionDetails): string {
  const data = jsonForHtml({
    schema: "agent-herder-session-graph/v1",
    evidence: "CANONICAL Agent Herder SessionDetails",
    session: details.session,
    lineage: details.lineage,
    children: details.children,
    history: details.history,
    messages: details.messages,
  });

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Agent Herder session graph · ${escapeHtml(details.session.title || details.session.id)}</title>
  <style>
    :root{color-scheme:dark;--bg:#0f0f11;--panel:#151517;--panel2:#19191c;--line:#2b2b31;--line2:#373740;--text:#f0eff3;--muted:#8c8993;--muted2:#66636d;--accent:#9b7bc2;--accentSoft:#241d2e;--blue:#6f9fe8;--green:#72c69d;--amber:#d7ab63;--red:#d66e78;--purple:#a77ac8;--cyan:#74b8b2}
    *{box-sizing:border-box}html,body{min-height:100%}body{margin:0;background:var(--bg);color:var(--text);font:12px/1.45 Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
    header{padding:16px 20px 14px;border-bottom:1px solid var(--line);position:sticky;top:0;z-index:4;background:#0f0f11f2;backdrop-filter:blur(16px)}
    .title-row{display:flex;align-items:flex-end;justify-content:space-between;gap:16px}.title-copy{min-width:0}.eyebrow{display:block;color:var(--accent);font-size:9px;font-weight:700;letter-spacing:.16em;text-transform:uppercase;margin-bottom:4px}h1{font:650 18px/1.2 Inter,ui-sans-serif,sans-serif;margin:0}.sub{margin-top:5px;color:var(--muted);font:10px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
    .controls{display:grid;grid-template-columns:auto minmax(220px,1fr) auto auto;gap:8px;align-items:center;margin-top:13px}.transport,.view-controls{display:flex;gap:5px;align-items:center}.control-sep{width:1px;height:22px;background:var(--line);margin:0 2px}
    input[type=range]{width:100%;accent-color:var(--accent)}button,input[type=search]{height:30px;border:1px solid var(--line);background:#17171a;color:var(--text);border-radius:7px;padding:5px 9px;font:10px/1.2 inherit;outline:none}button{cursor:pointer;transition:.12s ease}button:hover{border-color:#56505f;background:#1d1b21}button.active{border-color:#755c91;background:var(--accentSoft);color:#c9b2e2}#clock{min-width:150px;color:#b9b5bf;font:10px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;text-align:right}#search{width:180px;background:#131315}
    .layout{display:grid;grid-template-columns:minmax(0,1fr) 320px;min-height:calc(100vh - 104px)}.graph-wrap{min-width:0;overflow:auto;padding:16px 18px 28px}.inspect{border-left:1px solid var(--line);background:#121214;padding:18px;overflow:auto;max-height:calc(100vh - 104px);position:sticky;top:104px}
    .legend{display:flex;gap:13px;flex-wrap:wrap;color:var(--muted);margin:0 0 10px;font-size:10px}.legend span{display:inline-flex;align-items:center}.dot{width:7px;height:7px;border-radius:50%;display:inline-block;margin-right:6px}.summary{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}.summary span{padding:4px 7px;border:1px solid var(--line);border-radius:999px;background:#151517;color:var(--muted);font-size:9px}.count{color:#d8c3ef;font-weight:700}
    svg{display:block;min-width:900px;border:1px solid var(--line);border-radius:12px;background:linear-gradient(180deg,#141416,#111113);box-shadow:0 10px 28px #0005}.lane{stroke:#2d2d33;stroke-width:1}.lane-label{fill:#a9a5af;font-size:10px}.event,.message-node,.subagent-node{cursor:pointer;stroke:#121214;stroke-width:2;transition:.12s}.event:hover,.message-node:hover,.subagent-node:hover{filter:brightness(1.2)}.event.future,.message-node.future,.subagent-node.future{opacity:.12;pointer-events:none}.event.selected,.message-node.selected,.subagent-node.selected{stroke:#f7f4fa;stroke-width:2.5}.message-node.user{fill:var(--blue)}.message-node.assistant{fill:var(--green)}.message-node.tool{fill:var(--purple)}.message-node.system{fill:var(--muted)}.subagent-node{fill:var(--purple);stroke-width:2.5}.subagent-link{stroke:#8a6bab;stroke-width:1;stroke-dasharray:3 4;opacity:.5}.edge{stroke:#55515c;stroke-width:1;opacity:.22}.file-node{cursor:pointer}.file-node rect{fill:#171b1d;stroke:#343b40}.file-node:hover rect,.file-node.selected rect{stroke:var(--cyan);stroke-width:1.5}.file-node text{fill:#c8c7cd;font-size:9.5px}.future-file{opacity:.12;pointer-events:none}.duration-marker{stroke:#59565f;stroke-dasharray:3 4;opacity:.8}.duration-label{fill:#78747e;font-size:9px}.now-marker{stroke:var(--accent);stroke-dasharray:4 4;opacity:.85}.now-label{fill:#bca2d7;font-size:9px;font-weight:700}
    .panel-title{font:650 14px/1.35 Inter,ui-sans-serif,sans-serif;margin:0 0 10px}.meta{color:var(--muted);white-space:pre-wrap;overflow-wrap:anywhere;font:10px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.file-path{color:#b6d4d1;overflow-wrap:anywhere;margin:8px 0 14px;font:10px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}.message-body{white-space:pre-wrap;overflow-wrap:anywhere;border:1px solid var(--line);border-left:2px solid var(--blue);border-radius:8px;padding:11px;background:#0e0e10;max-height:50vh;overflow:auto;font-size:11px}.change{border:1px solid var(--line);border-radius:8px;margin:0 0 10px;overflow:hidden}.change-head{padding:7px 9px;background:#19191c;color:#aaa6b0;font-size:9px}.change pre{margin:0;padding:11px;overflow:auto;max-height:35vh;color:#d3d1d7;background:#0e0e10;font-size:10px}.notice{padding:10px;border:1px solid var(--line);border-radius:8px;background:#151517;color:var(--muted);font-size:10px}
    .sessions{margin-top:10px;display:flex;gap:6px;flex-wrap:wrap}.session-pill{font-size:9px;padding:4px 7px;border:1px solid var(--line);border-radius:999px;color:#aaa6b0;cursor:pointer;background:#151517}.session-pill:hover,.session-pill.selected{border-color:#6d587f;color:#ddd4e6;background:var(--accentSoft)}.line-mode-note{color:var(--muted2);font-size:9px;margin:8px 2px 0}.jump-file{height:auto;margin:4px 4px 0 0}
    @media(max-width:980px){.layout{display:block}.inspect{position:static;max-height:none;border-left:0;border-top:1px solid var(--line)}.controls{grid-template-columns:auto 1fr auto}.controls #search{grid-column:1/-1;width:100%}}
    @media(max-width:620px){header{padding:12px}.controls{grid-template-columns:1fr}.transport,.view-controls{justify-content:flex-start}.graph-wrap{padding:10px}.title-row{display:block}#clock{text-align:left}.inspect{padding:14px}}
  </style>
</head>
<body>
  <header>
    <div class="title-row"><div class="title-copy"><span class="eyebrow">SESSION</span><h1>Trajectory</h1><div class="sub" id="subtitle"></div></div></div>
    <div class="controls">
      <div class="transport"><button id="back" title="Step backward">←</button><button id="play" title="Play timeline">▶</button><button id="forward" title="Step forward">→</button></div>
      <input id="time" type="range" min="0" max="1000" value="1000" aria-label="Session time">
      <strong id="clock"></strong>
      <div class="view-controls"><button id="rotate" title="Rotate timeline 90 degrees">Rotate</button><button id="line-mode" title="Toggle single-line mode">Line</button><span class="control-sep"></span><input id="search" type="search" placeholder="Filter files…" aria-label="Filter files"></div>
    </div>
  </header>
  <main class="layout">
    <section class="graph-wrap">
      <div class="legend"><span><i class="dot" style="background:var(--blue)"></i>Messages</span><span><i class="dot" style="background:var(--cyan)"></i>Files</span><span><i class="dot" style="background:var(--purple)"></i>Tools / git</span><span><i class="dot" style="background:var(--amber)"></i>Current point</span></div>
      <div class="summary" id="summary"></div><svg id="graph" aria-label="Session message and file graph"></svg>
      <div class="sessions" id="sessions"></div>
      <div class="line-mode-note">Click a message, event, file, or child session for the selected detail. The slider controls the visible moment; ▶ plays it forward.</div>
    </section>
    <aside class="inspect" id="inspect"><h2 class="panel-title">Trajectory details</h2><div class="notice">Select a message, event, file, or child session to inspect it.</div></aside>
  </main>
  <script id="session-data" type="application/json">${data}</script>
  <script>
    const DATA=JSON.parse(document.getElementById('session-data').textContent);
    const COLORS={files:'#48d9c7',test:'#67a9ff',git:'#bb8cff',runtime:'#ffc65c',error:'#ff6b76'};
    const $=id=>document.getElementById(id);
    const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const parsed=value=>{const n=Date.parse(value||'');return Number.isFinite(n)?n:null};
    const fmt=ts=>new Date(ts).toLocaleString('ru-RU',{timeZone:'Europe/Moscow',hour12:false});
    const shortPath=(path,n=36)=>path.length<=n?path:'…'+path.slice(-(n-1));
    const duration=seconds=>seconds<60?Math.round(seconds)+'s':Math.floor(seconds/60)+'m '+Math.round(seconds%60)+'s';
    const root=DATA.session;
    const rootId=root.id;
    const childSessions=(DATA.children||[]).map(child=>({...child,sessionId:child.id}));
    const sessions=[{...root,sessionId:rootId,depth:0,source:'root'},...childSessions.map(child=>({...child,depth:1,source:child.harness}))];
    const fallback=parsed(root.lastActivity)||Date.now();
    const subagentMarkers=childSessions.map(child=>({...child,ts:parsed(child.lastActivity)||fallback}));
    const messages=(DATA.messages||[]).map((message,index)=>({...message,session:rootId,ts:parsed(message.timestamp)||fallback+index})).sort((a,b)=>a.ts-b.ts);
    const commandOf=part=>{if(typeof part.input==='string')return part.input;if(part.input&&typeof part.input==='object'){const value=part.input;for(const key of ['command','cmd','script','query','input'])if(typeof value[key]==='string')return value[key];return JSON.stringify(value)}return part.text||part.output||''};
    const pathsOf=command=>{const found=command.match(/(?:^|[\\s"'])((?:\\.?\\/?|~\\/)[^\\s"']+|(?:src|test|tests|app|lib|packages|integrations)\\/[A-Za-z0-9_./-]+\\.[A-Za-z0-9_-]+)(?=$|[\\s"',;:)])/g)||[];return [...new Set(found.map(value=>value.trim().replace(/^["']/,'').replace(/["',;:)]+$/,'')))].filter(value=>/\\.[A-Za-z0-9_-]+$/.test(value))};
    const kindOf=(part,command,paths)=>{const lower=(part.name||'')+' '+command.toLowerCase();if(part.error||/\\b(error|failed|failure)\\b/.test(lower))return 'error';if(/\\b(git|commit|checkout|merge|branch|diff)\\b/.test(lower))return 'git';if(/\\b(test|vitest|jest|pytest|npm run build|tsc|lint)\\b/.test(lower))return 'test';if(/\\b(deploy|systemctl|restart|curl|docker|nginx)\\b/.test(lower))return 'runtime';if(paths.length||/\\b(apply_patch|write|edit|create|delete|mkdir|mv|cp|tee|sed -i)\\b/.test(lower))return 'files';return null};
    const events=[];const fileMap=new Map();
    const addFile=(path,event,command)=>{if(!fileMap.has(path))fileMap.set(path,{id:'file-'+fileMap.size,path,scope:root.cwd,evidence:'CANONICAL tool_call',changes:[]});fileMap.get(path).changes.push({event:event.id,ts:event.ts,time:event.time,operation:event.kind,command,session:rootId,diff:''})};
    messages.forEach((message,messageIndex)=>{(message.parts||[]).forEach((part,partIndex)=>{if(part.type!=='tool_call'&&part.type!=='tool_result')return;const command=commandOf(part);const paths=pathsOf(command);const kind=kindOf(part,command,paths);if(!kind)return;const event={id:'event-'+messageIndex+'-'+partIndex,ts:message.ts,time:fmt(message.ts),kind,session:rootId,tool:part.name||part.type,outcome:part.error?'error':'recorded',evidence:'CANONICAL tool_call',detail:command||part.name||part.type,files:paths};events.push(event);paths.forEach(path=>addFile(path,event,command));})});
    const files=[...fileMap.values()];
    const start=Math.min(...[...messages.map(message=>message.ts),...events.map(event=>event.ts),...subagentMarkers.map(child=>child.ts),fallback]);
    const end=Math.max(...[...messages.map(message=>message.ts),...events.map(event=>event.ts),...subagentMarkers.map(child=>child.ts),fallback]);
    const span=Math.max(1,end-start);
    let selectedTs=end,selectedFile=null,selectedEvent=null,selectedMessage=null,selectedSession=null,timer=null,vertical=false,lineMode=false;
    const timeToSlider=ts=>Math.max(0,Math.min(1000,Math.round((ts-start)/span*1000)));
    const sliderToTs=()=>start+(Number($('time').value)/1000)*span;
    const titleForMessage=message=>'#'+(messages.indexOf(message)+1)+' · '+message.role+' · '+fmt(message.ts);
    const sessionLabel=session=>session.depth?((session.meta&&session.meta.agentRole)||session.harness)+' · '+session.sessionId.slice(0,8):(session.title||session.sessionId.slice(0,10));
    $('subtitle').textContent=root.harness+' · '+root.id+' · '+(root.cwd||'');
    $('sessions').innerHTML=sessions.map(session=>'<span class="session-pill" data-session="'+esc(session.sessionId)+'">'+(session.depth?'↳ child':'root')+' · '+esc(session.title||session.sessionId)+' · '+esc(session.harness)+'</span>').join('');
    $('sessions').querySelectorAll('[data-session]').forEach(node=>node.onclick=()=>showSession(node.dataset.session));
    function setSummary(activeMessages,activeEvents,visibleFiles){$('summary').innerHTML='<span><b class="count">'+activeMessages+'</b> Messages</span><span><b class="count">'+activeEvents+'</b> events</span><span><b class="count">'+visibleFiles+'</b> files at selected time</span><span>'+sessions.length+' session lane(s)</span>'}
    function render(){selectedTs=sliderToTs();$('clock').textContent=fmt(selectedTs);renderGraph();if(selectedFile)showFile(selectedFile,false);else if(selectedEvent)showEvent(selectedEvent,false);else if(selectedMessage)showMessage(selectedMessage,false);else if(selectedSession)showSession(selectedSession,false)}
    function renderGraph(){
      const query=$('search').value.toLowerCase();const activeEvents=events.filter(event=>event.ts<=selectedTs);const activeMessages=messages.filter(message=>message.ts<=selectedTs);const visibleFiles=files.filter(file=>file.path.toLowerCase().includes(query)&&file.changes.some(change=>change.ts<=selectedTs)).sort((left,right)=>right.changes[right.changes.length-1].ts-left.changes[left.changes.length-1].ts).slice(0,160);
      const laneH=66,labelW=175,plotW=920,fileCols=3,fileW=270,fileH=35;const laneCount=lineMode?1:sessions.length;const laneIndex=new Map(sessions.map((session,index)=>[session.sessionId,lineMode?0:index]));const fileBase=lineMode?128:laneCount*laneH+58;const fileRows=lineMode?0:Math.ceil(visibleFiles.length/fileCols);const timelineHeight=vertical?780:0;const width=vertical?Math.max(900,labelW+laneCount*laneH+180):labelW+plotW+40;const height=vertical?timelineHeight+fileRows*fileH+105:Math.max(220,fileBase+fileRows*fileH+48);let out='';const eventPos=new Map();
      const laneY=index=>lineMode?68:35+index*laneH;const timeX=ts=>labelW+((ts-start)/span)*plotW;const timeY=ts=>55+((ts-start)/span)*timelineHeight;
      if(vertical){sessions.slice(0,laneCount).forEach((session,index)=>{const x=labelW+38+index*laneH;out+='<line class="lane" x1="'+x+'" y1="55" x2="'+x+'" y2="'+(55+timelineHeight)+'"/><text class="lane-label" x="'+x+'" y="28" transform="rotate(-55 '+x+' 28)">'+esc(sessionLabel(session))+'</text>'})}else{sessions.forEach((session,index)=>{const y=laneY(index);out+='<line class="lane" x1="'+labelW+'" y1="'+y+'" x2="'+(labelW+plotW)+'" y2="'+y+'"/><text class="lane-label" x="'+(10+session.depth*10)+'" y="'+(y+4)+'"><title>'+esc(session.title||session.sessionId)+'</title>'+(session.depth?'↳ ':'')+esc(sessionLabel(session))+'</text>'})}
      events.forEach(event=>{const position=vertical?[labelW+38+((laneIndex.get(event.session)||0)*laneH),timeY(event.ts)]:[timeX(event.ts),laneY(laneIndex.get(event.session)||0)];eventPos.set(event.id,position)});
      subagentMarkers.forEach(child=>{const lane=laneIndex.get(child.sessionId)||0;const x=vertical?labelW+38+lane*laneH:timeX(child.ts);const y=vertical?timeY(child.ts):laneY(lane);const future=child.ts>selectedTs;const href=child.harness==='codex'?'codex://threads/'+encodeURIComponent(child.sessionId):'#';out+='<line class="subagent-link" x1="'+(vertical?x:x-18)+'" y1="'+(vertical?y:y-18)+'" x2="'+(vertical?x:x+18)+'" y2="'+(vertical?y:y+18)+'"/><a href="'+esc(href)+'"'+(href==='#'?'':' target="_blank" rel="noreferrer"')+'"><circle class="subagent-node '+(future?'future ':'')+(selectedSession===child.sessionId?'selected':'')+'" data-session="'+esc(child.sessionId)+'" cx="'+x+'" cy="'+y+'" r="8"><title>'+esc((child.meta&&child.meta.agentRole||child.harness)+' · '+child.sessionId+' · '+fmt(child.ts))+'</title></circle></a>'});
      const durationGaps=[];for(let index=1;index<messages.length;index++){const gap=(messages[index].ts-messages[index-1].ts)/1000;if(gap>30)durationGaps.push({ts:messages[index].ts,previous:messages[index-1].ts,seconds:gap})}
      durationGaps.forEach(gap=>{if(vertical){const y1=timeY(gap.previous),y2=timeY(gap.ts),x=labelW+52; if(y2-y1>=30)out+='<line class="duration-marker" x1="'+(x-8)+'" y1="'+y1+'" x2="'+(x-8)+'" y2="'+y2+'"/><text class="duration-label" x="'+(x+2)+'" y="'+((y1+y2)/2)+'">'+duration(gap.seconds)+'</text>'}else{const x1=timeX(gap.previous),x2=timeX(gap.ts);if(x2-x1>=34)out+='<line class="duration-marker" x1="'+x1+'" y1="'+(laneY(0)-24)+'" x2="'+x2+'" y2="'+(laneY(0)-24)+'"/><text class="duration-label" x="'+((x1+x2)/2-12)+'" y="'+(laneY(0)-29)+'">'+duration(gap.seconds)+'</text>'}});
      const fromPosition=vertical?[labelW+38+((laneIndex.get(rootId)||0)*laneH),timeY(start)]:[timeX(start),laneY(0)-24];const nowPosition=vertical?[labelW+38+((laneIndex.get(rootId)||0)*laneH),timeY(end)]:[timeX(end),laneY(0)-24];out+='<text class="lane-label" x="'+(vertical?fromPosition[0]+23:fromPosition[0]+5)+'" y="'+(vertical?fromPosition[1]-5:fromPosition[1]-12)+'">FROM</text><line class="now-marker" x1="'+(vertical?nowPosition[0]-18:nowPosition[0])+'" y1="'+(vertical?nowPosition[1]:nowPosition[1]-10)+'" x2="'+(vertical?nowPosition[0]+18:nowPosition[0])+'" y2="'+(vertical?nowPosition[1]:nowPosition[1]+10)+'"/><text class="now-label" x="'+(vertical?nowPosition[0]+23:nowPosition[0]+5)+'" y="'+(vertical?nowPosition[1]-5:nowPosition[1]-12)+'">NOW</text>';
      activeEvents.forEach(event=>{const p=eventPos.get(event.id);if(!p)return;const future=event.ts>selectedTs;out+='<circle class="event '+(future?'future ':'')+(selectedEvent===event.id?'selected':'')+'" data-event="'+esc(event.id)+'" cx="'+p[0]+'" cy="'+p[1]+'" r="7" fill="'+(COLORS[event.kind]||COLORS.files)+'"><title>'+esc(event.time+' · '+event.kind+' · '+event.detail)+'</title></circle>'});
      messages.forEach(message=>{const lane=laneIndex.get(message.session)||0;const x=vertical?labelW+38+lane*laneH+(message.role==='user'?-13:13):timeX(message.ts);const y=vertical?timeY(message.ts):laneY(lane)+(message.role==='user'?-13:13);const future=message.ts>selectedTs;const fill=message.role==='user'?'var(--blue)':message.role==='assistant'?'var(--green)':message.role==='tool'?'var(--purple)':'var(--muted)';out+='<rect class="message-node '+message.role+' '+(future?'future ':'')+(selectedMessage===message.id?'selected':'')+'" data-message="'+esc(message.id)+'" x="'+(x-5)+'" y="'+(y-5)+'" width="10" height="10" fill="'+fill+'" transform="rotate(45 '+x+' '+y+')"><title>'+esc(titleForMessage(message))+'</title></rect>'});
      if(!lineMode){visibleFiles.forEach((file,index)=>{const x=vertical?labelW+12+(index%fileCols)*(fileW+20):labelW+12+(index%fileCols)*(fileW+20);const y=vertical?timelineHeight+55+Math.floor(index/fileCols)*fileH:fileBase+Math.floor(index/fileCols)*fileH;const changes=file.changes.filter(change=>change.ts<=selectedTs);const latest=changes.at(-1);if(latest){const p=eventPos.get(latest.event);if(p)out+='<line class="edge" x1="'+p[0]+'" y1="'+p[1]+'" x2="'+(x+fileW/2)+'" y2="'+(y+13)+'"/>'}out+='<g class="file-node '+(selectedFile===file.id?'selected':'')+'" data-file="'+esc(file.id)+'" transform="translate('+x+','+y+')"><rect width="'+fileW+'" height="27" rx="6"/><text x="9" y="18">'+esc(shortPath(file.path))+'</text><title>'+esc(file.path)+'</title></g>'})}else{visibleFiles.forEach(file=>file.changes.filter(change=>change.ts<=selectedTs&&file.path.toLowerCase().includes(query)).forEach(change=>{const p=eventPos.get(change.event);if(!p)return;const x=vertical?p[0]:p[0],y=vertical?p[1]:p[1]+30;out+='<circle class="event" data-file="'+esc(file.id)+'" cx="'+x+'" cy="'+y+'" r="4" fill="'+COLORS.files+'"><title>'+esc(file.path)+'</title></circle>'}))}
      if(vertical){out+='<text class="lane-label" x="10" y="'+(timelineHeight+34)+'">FILES @ TIME</text>'}else{out+='<text class="lane-label" x="10" y="'+(lineMode?fileBase+20:fileBase+17)+'">'+(lineMode?'LINE':'FILES @ TIME')+'</text>'}
      $('graph').setAttribute('viewBox','0 0 '+width+' '+height);$('graph').style.height=Math.max(260,height)+'px';$('graph').innerHTML=out;setSummary(activeMessages.length,activeEvents.length,visibleFiles.length+(files.length>visibleFiles.length?' (cap 160)':''));
      $('graph').querySelectorAll('[data-event]').forEach(node=>node.onclick=()=>showEvent(node.dataset.event));$('graph').querySelectorAll('[data-message]').forEach(node=>node.onclick=()=>showMessage(node.dataset.message));$('graph').querySelectorAll('[data-file]').forEach(node=>node.onclick=()=>showFile(node.dataset.file));$('graph').querySelectorAll('[data-session]').forEach(node=>node.onclick=()=>showSession(node.dataset.session));
    }
    function clearSelection(){selectedFile=selectedEvent=selectedMessage=selectedSession=null}
    function showEvent(id,rerender=true){clearSelection();selectedEvent=id;const event=events.find(item=>item.id===id);if(!event)return;if(rerender)renderGraph();$('inspect').innerHTML='<h2 class="panel-title">'+esc(event.kind)+' · '+esc(event.time)+'</h2><div class="meta">session '+esc(event.session)+'\\ntool '+esc(event.tool)+'\\noutcome '+esc(event.outcome)+'\\nevidence '+esc(event.evidence)+'</div><div class="file-path">'+esc(event.detail)+'</div>'+(event.files.length?'<div class="meta">files</div>'+event.files.map(path=>'<button class="jump-file" data-path="'+esc(path)+'">'+esc(shortPath(path,55))+'</button>').join(' '):'<div class="notice">No recorded file path on this event.</div>');$('inspect').querySelectorAll('.jump-file').forEach(node=>node.onclick=()=>{const file=files.find(item=>item.path===node.dataset.path);if(file)showFile(file.id)});}
    function showMessage(id,rerender=true){clearSelection();selectedMessage=id;const message=messages.find(item=>item.id===id);if(!message)return;if(rerender)renderGraph();$('inspect').innerHTML='<h2 class="panel-title">'+esc(message.role)+' message · '+esc(fmt(message.ts))+'</h2><div class="meta">session '+esc(message.session)+'\\nevidence CANONICAL Agent Herder SessionDetails\\nparts '+message.parts.length+'</div><br><div class="message-body">'+esc(message.text||'(no text; inspect tool events below)')+'</div>';}
    function showSession(id,rerender=true){clearSelection();selectedSession=id;const session=sessions.find(item=>item.sessionId===id);if(!session)return;if(rerender)renderGraph();const children=sessions.filter(item=>item.depth&&item.meta?.parentSessionKey===id);const threadUrl=session.harness==='codex'?'codex://threads/'+encodeURIComponent(session.sessionId):'';$('inspect').innerHTML='<h2 class="panel-title">'+(session.depth?'Child session':'Root session')+' · '+esc(session.title||session.sessionId)+'</h2><div class="meta">id '+esc(session.sessionId)+'\\nharness '+esc(session.harness)+'\\nstatus '+esc(session.status||'-')+'\\nparent '+esc(session.meta?.parentSessionKey||'-')+'\\nevidence CANONICAL Agent Herder SessionDetails</div>'+(threadUrl?'<br><a href="'+esc(threadUrl)+'">Open '+esc(threadUrl)+'</a>':'')+'<div class="notice">'+children.length+' child session(s) · '+messages.filter(message=>message.session===id&&message.ts<=selectedTs).length+' message(s) through selected time.</div>';}
    function showFile(id,rerender=true){clearSelection();selectedFile=id;const file=files.find(item=>item.id===id);if(!file)return;if(rerender)renderGraph();const changes=file.changes.filter(change=>change.ts<=selectedTs).sort((a,b)=>b.ts-a.ts);let body='<h2 class="panel-title">File changes @ '+esc(fmt(selectedTs))+'</h2><div class="file-path">'+esc(file.path)+'</div><div class="meta">scope '+esc(file.scope)+' · evidence '+esc(file.evidence)+' · '+changes.length+' change(s) through selected time</div><br>';if(!changes.length)body+='<div class="notice">No recorded change before the selected moment.</div>';for(const change of changes)body+='<article class="change"><div class="change-head">'+esc(change.time)+' · '+esc(change.operation)+' · session '+esc(change.session.slice(0,8))+'</div><pre>'+esc(change.diff||change.command||'Recorded tool operation; no diff payload available.')+'</pre></article>';$('inspect').innerHTML=body;}
    $('time').oninput=render;$('search').oninput=renderGraph;$('back').onclick=()=>{$('time').value=Math.max(0,Number($('time').value)-25);render()};$('forward').onclick=()=>{$('time').value=Math.min(1000,Number($('time').value)+25);render()};$('play').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('play').textContent='▶';return}if(Number($('time').value)>=1000)$('time').value=0;$('play').textContent='❚❚';timer=setInterval(()=>{let value=Number($('time').value)+5;if(value>=1000){value=1000;clearInterval(timer);timer=null;$('play').textContent='▶'}$('time').value=value;render()},40)};$('rotate').onclick=()=>{vertical=!vertical;$('rotate').classList.toggle('active',vertical);render()};$('line-mode').onclick=()=>{lineMode=!lineMode;$('line-mode').classList.toggle('active',lineMode);render()};
    $('time').value=1000;render();showSession(rootId,false);
  </script>
</body>
</html>`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[char] || char));
}
